<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Soring,-searching,-and-counting" data-toc-modified-id="Soring,-searching,-and-counting-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Soring, searching, and counting</a></span><ul class="toc-item"><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Sorting</a></span></li><li><span><a href="#Searching" data-toc-modified-id="Searching-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Searching</a></span></li><li><span><a href="#Counting" data-toc-modified-id="Counting-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Counting</a></span></li></ul></li></ul></div>

# Soring, searching, and counting

In [2]:
import numpy as np

## Sorting

Q1. Sort x along the second axis.

In [5]:
x = np.array([[1,4],[3,1]])
np.sort(x)

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [4]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
x = np.lexsort((surnames, first_names))
x

array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [3]:
x = np.array([[1,4],[3,1]])
np.argsort(x)

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [14]:
x = np.random.permutation(10)
sorted_x = np.sort(x)

result_array = np.zeros_like(x, dtype=float)
result_array[:-1] = x[:-1] / x[:-1]  
result_array[-1] = sorted_x[4]  

print("Початковий масив x:", x)
print("Відсортований масив x:", sorted_x)
print("Кінцевий результат:", result_array)


Початковий масив x: [8 1 5 0 4 3 2 9 7 6]
Відсортований масив x: [0 1 2 3 4 5 6 7 8 9]
Кінцевий результат: [ 1.  1.  1. nan  1.  1.  1.  1.  1.  4.]


C:\Users\Катерина\AppData\Local\Temp\ipykernel_15280\2923582284.py:5: RuntimeWarning: invalid value encountered in divide
  result_array[:-1] = x[:-1] / x[:-1]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [15]:
x = np.random.permutation(10)
sorted_x = np.sort(x)
indices = np.arange(len(x), dtype=float)
indices[:-1] = indices[:-1] / x[:-1]  
indices[-1] = sorted_x[2]  

print("Початковий масив x:", x)
print("Відсортований масив x:", sorted_x)
print("Масив індексів:", indices)


Original array x: [8 7 6 1 5 9 2 3 0 4]
Sorted array x: [0 1 2 3 4 5 6 7 8 9]
Indices array: [0.         0.14285714 0.33333333 3.         0.8        0.55555556
 3.         2.33333333        inf 2.        ]


C:\Users\Катерина\AppData\Local\Temp\ipykernel_15280\3487131020.py:6: RuntimeWarning: divide by zero encountered in divide
  indices[:-1] = indices[:-1] / x[:-1]  # Divide all elements by their values except the last one


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [6]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)
print("maximum values =", np.max(x, axis=1))
print("indeces of maximum values =", np.argmax(x, axis=1))
print("minimum values =", np.min(x, axis=1))
print("indeces of minimum values =", np.argmin(x, axis=1))


x = [[0 8 9 6 1]
 [5 2 4 7 3]]
maximum values = [9 7]
indeces of maximum values = [2 3]
minimum values = [0 2]
indeces of minimum values = [0 1]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [7]:
x = np.array([[np.nan, 4], [3, 2]])
print("maximum values ignoring NaNs =", np.nanmax(x, axis=1))
print("max indices =", np.nanargmax(x, axis=1))
print("minimum values ignoring NaNs =", np.nanmin(x, axis=1))
print("min indices =", np.nanargmin(x, axis=1))

maximum values ignoring NaNs = [4. 3.]
max indices = [1 0]
minimum values ignoring NaNs = [4. 2.]
min indices = [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [8]:
x = np.array([[1, 2, 3], [1, 3, 5]])
bigger_than_2 = x[x>2]
print("Values bigger than 2 =", bigger_than_2)
print("Their indices are ", np.nonzero(x > 2))

Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [9]:
x = np.array([[1, 2, 3], [1, 3, 5]])
np.flatnonzero(x>2)

array([2, 4, 5], dtype=int64)

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [10]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x <0, 0, x)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [11]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y)

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [12]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5