<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Soring,-searching,-and-counting" data-toc-modified-id="Soring,-searching,-and-counting-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Soring, searching, and counting</a></span><ul class="toc-item"><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Sorting</a></span></li><li><span><a href="#Searching" data-toc-modified-id="Searching-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Searching</a></span></li><li><span><a href="#Counting" data-toc-modified-id="Counting-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Counting</a></span></li></ul></li></ul></div>

# Soring, searching, and counting

In [30]:
import numpy as np

## Sorting

Q1. Sort x along the second axis.

In [2]:
x = np.array([[1,4],[3,1]])
np.sort(x)

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [4]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [6]:
x = np.array([[1,4],[3,1]])
np.argsort(x)

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

C:\Users\Asus\AppData\Local\Temp\ipykernel_8996\371324353.py:5: RuntimeWarning: invalid value encountered in divide
  result[:4] = x[:4] / x[:4]


array([          1,           1, -2147483648,           1,           4,
                 1,           1,           1,           1,           1])

Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

C:\Users\Asus\AppData\Local\Temp\ipykernel_8996\764844988.py:5: RuntimeWarning: invalid value encountered in divide
  indices[:2] = indices[:2] / indices[:2]
C:\Users\Asus\AppData\Local\Temp\ipykernel_8996\764844988.py:6: RuntimeWarning: invalid value encountered in divide
  indices[4:] = indices[4:] / indices[4:]


array([-2147483648, -2147483648,           9,           0, -2147483648,
       -2147483648, -2147483648, -2147483648, -2147483648, -2147483648])

## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [35]:
x = np.random.permutation(10).reshape(2, 5)
max_values = np.max(x, axis=1)
min_values = np.min(x, axis=1)
max_indices = np.argmax(x, axis=1)
min_indices = np.argmin(x, axis=1)

print("original x:")
print(x)
print("\nmaximum values:", max_values)
print("indices of maximum:", max_indices)
print("\nminimum values:", min_values)
print("indices of minimum:", min_indices)

original x:
[[4 9 6 7 3]
 [5 8 2 0 1]]

maximum values: [9 8]
indices of maximum: [1 1]

minimum values: [3 0]
indices of minimum: [4 3]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [36]:
x = np.array([[np.nan, 4], [3, 2]])
max_values = np.nanmax(x, axis=1)
min_values = np.nanmin(x, axis=1)
max_indices = np.nanargmax(x, axis=1)
min_indices = np.nanargmin(x, axis=1)
print("\nmaximum values ignoring NaNs:", max_values)
print("indices of maximum :", max_indices)
print("\nminimum values ignoring NaNs:", min_values)
print("indices of minimum:", min_indices)


maximum values ignoring NaNs: [4. 3.]
indices of maximum : [1 0]

minimum values ignoring NaNs: [4. 2.]
indices of minimum: [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [40]:
x = np.array([[1, 2, 3], [1, 3, 5]])
a = x[x>2]
y = np.where(x>2)
print('values bigger than 2:', a)
print('indices:', y)


values bigger than 2: [3 3 5]
indices: (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [45]:
x = np.array([[1, 2, 3], [1, 3, 5]])
f = x.flatten()
np.where(f>2)

(array([2, 4, 5], dtype=int64),)

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [46]:
x = np.arange(-5, 4).reshape(3, 3)
result = np.where(x < 0, 0, x)
result

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [47]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
i = np.searchsorted(x, y)
i

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [48]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5